# This is a config for E2B sandbox template.
# You can use template ID (xpw2sii2jq0i96m9m4xy) or template name (ai-website-builder-1234) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("ai-website-builder-1234") # Sync sandbox
# sandbox = await AsyncSandbox.create("ai-website-builder-1234") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ai-website-builder-1234')

team_id = "366a0e01-2df2-4563-902a-49d6fb6817a9"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "ai-website-builder-1234"
template_id = "xpw2sii2jq0i96m9m4xy"
